// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm3nhkQ_MwmeYPPDiKSDlzefzA6-9QmkA',
    appId: '1:756565377270:web:7ef7664be347a7528e6cd7',
    messagingSenderId: '756565377270',
    projectId: 'myroute-ap',
    authDomain: 'myroute-ap.firebaseapp.com',
    storageBucket: 'myroute-ap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBXE-21I83kqmne8aGH5ncehNy0nIVeTQ',
    appId: '1:756565377270:android:69557c05e2514a798e6cd7',
    messagingSenderId: '756565377270',
    projectId: 'myroute-ap',
    storageBucket: 'myroute-ap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNzDu-taedMeykLhmDvy-CQJHHy9ZkvPY',
    appId: '1:756565377270:ios:04d3651f2bfbf4bb8e6cd7',
    messagingSenderId: '756565377270',
    projectId: 'myroute-ap',
    storageBucket: 'myroute-ap.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNzDu-taedMeykLhmDvy-CQJHHy9ZkvPY',
    appId: '1:756565377270:ios:04d3651f2bfbf4bb8e6cd7',
    messagingSenderId: '756565377270',
    projectId: 'myroute-ap',
    storageBucket: 'myroute-ap.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm3nhkQ_MwmeYPPDiKSDlzefzA6-9QmkA',
    appId: '1:756565377270:web:2c9369dc6d5ba59c8e6cd7',
    messagingSenderId: '756565377270',
    projectId: 'myroute-ap',
    authDomain: 'myroute-ap.firebaseapp.com',
    storageBucket: 'myroute-ap.firebasestorage.app',
  );
}
